repos:
  # Spelling: Checks for common misspellings in text files.
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types: [text]
        args: [--exclude-file=pnpm-lock.yaml]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pycontribs/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        args: [--ignore-unknown, --no-error-on-unmatched-pattern, '!pnpm-lock.yaml']

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [--fix, --ignore, .github]
